### create new user
POST http://localhost:3000/user/
Content-Type: application/json

{
    "name":"hema",
    "username":"hemausername",
    "password":"123456Hr",
    "email":"hema@gmail.com"
}

### find user by id
Get http://localhost:3000/user/9dab2779-a00c-4946-b178-fad2fa94438e

### update user
PUT http://localhost:3000/user/9dab2779-a00c-4946-b178-fad2fa94438e
content-type:application/json

{
    "name":"hema2",
    "username":"justhema",
    "password":"123456Hr",
    "email":"hema2@gmail.com"
}

### get all users paginated
GET http://localhost:3000/user/all?page=1&limit=500

### login user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"hema@gmail.com",
    "password":"123456Hr"
}